/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import esper.config;
import events.AverageSpeedMonitoring;
import events.Calibrating;
import events.CruiseControlMonitoring;
import events.FuelConsumptionMonitoring;
import events.MaintenanceMonitoring;
import events.SpeedEvent;
import events.VehicleRunning;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.JToggleButton;
import model.CruiseControlCommand;
import model.Vehicle;

/**
 *
 * @author DELL
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.STOPcalibratebutton.setEnabled(false);
        this.acivate.setEnabled(false);
        this.averagespeedbtn.setEnabled(false);
        this.brake.setEnabled(false);
        this.calibratebutton.setEnabled(false);
        this.deactivate.setEnabled(false);
        this.eight.setEnabled(false);
        this.eightvolt.setEnabled(false);
        this.enter.setEnabled(false);
        this.five.setEnabled(false);
        this.fivevolt.setEnabled(false);
        this.four.setEnabled(false);
        this.fourvolt.setEnabled(false);
        this.nine.setEnabled(false);
        this.one.setEnabled(false);
        this.onevolt.setEnabled(false);
        this.resume.setEnabled(false);
        this.servicecompleted.setEnabled(false);
        this.seven.setEnabled(false);
        this.sevenvolt.setEnabled(false);
        this.six.setEnabled(false);
        this.sixvolt.setEnabled(false);
        this.starttripbtn.setEnabled(false);
        this.three.setEnabled(false);
        this.threevolt.setEnabled(false);
        this.two.setEnabled(false);
        this.twovolt.setEnabled(false);
        this.zero.setEnabled(false);
    }

    public JToggleButton getServicecompleted() {
        return servicecompleted;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EngineButton = new javax.swing.JToggleButton();
        CruiseControl = new javax.swing.JPanel();
        deactivate = new javax.swing.JToggleButton();
        resume = new javax.swing.JToggleButton();
        acivate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        calibratebutton = new javax.swing.JToggleButton();
        STOPcalibratebutton = new javax.swing.JToggleButton();
        CalibrationDistance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        driveShaftPulse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        averagespeed = new javax.swing.JPanel();
        starttripbtn = new javax.swing.JButton();
        averagespeedbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        currentSpeed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        averageSpeedDisplay = new javax.swing.JTextField();
        distance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        onevolt = new javax.swing.JButton();
        twovolt = new javax.swing.JButton();
        threevolt = new javax.swing.JButton();
        fourvolt = new javax.swing.JButton();
        fivevolt = new javax.swing.JButton();
        sixvolt = new javax.swing.JButton();
        sevenvolt = new javax.swing.JButton();
        eightvolt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        brake = new javax.swing.JToggleButton();
        keyboard = new javax.swing.JPanel();
        zero = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        fuelEntered = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        oilLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        airfilter = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        major = new javax.swing.JLabel();
        servicecompleted = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        EngineButton.setText("Engine ON/OFF");
        EngineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineButtonActionPerformed(evt);
            }
        });

        deactivate.setText("Deactivate");
        deactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateActionPerformed(evt);
            }
        });

        resume.setText("Resume");
        resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeActionPerformed(evt);
            }
        });

        acivate.setText("Activate");
        acivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CruiseControlLayout = new javax.swing.GroupLayout(CruiseControl);
        CruiseControl.setLayout(CruiseControlLayout);
        CruiseControlLayout.setHorizontalGroup(
            CruiseControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CruiseControlLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(CruiseControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deactivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        CruiseControlLayout.setVerticalGroup(
            CruiseControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CruiseControlLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(acivate)
                .addGap(36, 36, 36)
                .addComponent(deactivate)
                .addGap(47, 47, 47)
                .addComponent(resume)
                .addGap(43, 43, 43))
        );

        calibratebutton.setText("START_CALIBRATE");
        calibratebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calibratebuttonActionPerformed(evt);
            }
        });

        STOPcalibratebutton.setText("STOP_CALIBRATE");
        STOPcalibratebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STOPcalibratebuttonActionPerformed(evt);
            }
        });

        CalibrationDistance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CalibrationDistance.setText("2");
        CalibrationDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalibrationDistanceActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Pre-Defined Distance KM");

        driveShaftPulse.setEditable(false);
        driveShaftPulse.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setText("Drive Shaft Pulses");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(CalibrationDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(STOPcalibratebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calibratebutton))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(driveShaftPulse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(calibratebutton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(STOPcalibratebutton)
                    .addComponent(driveShaftPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalibrationDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        starttripbtn.setText("START_TRIP");
        starttripbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starttripbtnActionPerformed(evt);
            }
        });

        averagespeedbtn.setText("AVERAGE_SPEED");
        averagespeedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averagespeedbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout averagespeedLayout = new javax.swing.GroupLayout(averagespeed);
        averagespeed.setLayout(averagespeedLayout);
        averagespeedLayout.setHorizontalGroup(
            averagespeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(averagespeedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(averagespeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(averagespeedbtn)
                    .addComponent(starttripbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        averagespeedLayout.setVerticalGroup(
            averagespeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(averagespeedLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(starttripbtn)
                .addGap(18, 18, 18)
                .addComponent(averagespeedbtn)
                .addContainerGap())
        );

        currentSpeed.setEditable(false);
        currentSpeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currentSpeed.setText("0");
        currentSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentSpeedActionPerformed(evt);
            }
        });

        jLabel1.setText("Speed KM/h");

        averageSpeedDisplay.setEditable(false);
        averageSpeedDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        averageSpeedDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageSpeedDisplayActionPerformed(evt);
            }
        });

        distance.setEditable(false);
        distance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceActionPerformed(evt);
            }
        });

        jLabel2.setText("Average Speed KM/h");

        jLabel3.setText("Distance KM");

        jTextField1.setText("Engine OFF");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Fuel Consumption");

        jLabel6.setText("Fuel left");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(distance, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(averageSpeedDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(averageSpeedDisplay)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addGap(16, 16, 16))
        );

        jPanel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel4PropertyChange(evt);
            }
        });

        onevolt.setText("1 volts");
        onevolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onevoltActionPerformed(evt);
            }
        });

        twovolt.setText("2 Volts");
        twovolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twovoltActionPerformed(evt);
            }
        });

        threevolt.setText("3 Volts");
        threevolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threevoltActionPerformed(evt);
            }
        });

        fourvolt.setText("4 Volts");
        fourvolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourvoltActionPerformed(evt);
            }
        });

        fivevolt.setText("5 Volts");
        fivevolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivevoltActionPerformed(evt);
            }
        });

        sixvolt.setText("6 Volts");
        sixvolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixvoltActionPerformed(evt);
            }
        });

        sevenvolt.setText("7 Volts");
        sevenvolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenvoltActionPerformed(evt);
            }
        });

        eightvolt.setText("8 Volts");
        eightvolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightvoltActionPerformed(evt);
            }
        });

        jLabel8.setText("Accelerator Pedal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sevenvolt)
                        .addGap(18, 18, 18)
                        .addComponent(eightvolt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(onevolt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(twovolt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(threevolt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fourvolt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(fivevolt)
                        .addGap(18, 18, 18)
                        .addComponent(sixvolt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onevolt)
                    .addComponent(twovolt))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threevolt)
                    .addComponent(fourvolt))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fivevolt)
                    .addComponent(sixvolt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eightvolt)
                    .addComponent(sevenvolt))
                .addContainerGap())
        );

        brake.setText("Brake ");
        brake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brake, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(brake, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        fuelEntered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelEnteredActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout keyboardLayout = new javax.swing.GroupLayout(keyboard);
        keyboard.setLayout(keyboardLayout);
        keyboardLayout.setHorizontalGroup(
            keyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fuelEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(keyboardLayout.createSequentialGroup()
                .addGroup(keyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(keyboardLayout.createSequentialGroup()
                        .addGroup(keyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(keyboardLayout.createSequentialGroup()
                                .addComponent(zero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(one)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two))
                            .addGroup(keyboardLayout.createSequentialGroup()
                                .addComponent(four)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(five)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(six)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(keyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seven)
                            .addGroup(keyboardLayout.createSequentialGroup()
                                .addComponent(three)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton))))
                    .addGroup(keyboardLayout.createSequentialGroup()
                        .addComponent(eight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        keyboardLayout.setVerticalGroup(
            keyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fuelEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(keyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zero)
                    .addComponent(one)
                    .addComponent(two)
                    .addComponent(three)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four)
                    .addComponent(five)
                    .addComponent(six)
                    .addComponent(seven))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(keyboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eight)
                    .addComponent(nine)
                    .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(oilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oilLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(airfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(airfilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(major, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(major, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        servicecompleted.setText("Service Completed");
        servicecompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicecompletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keyboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(averagespeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(servicecompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EngineButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CruiseControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EngineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(CruiseControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(averagespeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(keyboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(servicecompleted)
                            .addGap(27, 27, 27)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EngineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineButtonActionPerformed
        // TODO add your handling code here:
        if (EngineButton.isSelected()) {
            config.sendEvent(new VehicleRunning(true));
            this.STOPcalibratebutton.setEnabled(true);
            this.STOPcalibratebutton.setEnabled(true);
            this.acivate.setEnabled(true);
            this.averagespeedbtn.setEnabled(true);
            this.brake.setEnabled(true);
            this.calibratebutton.setEnabled(true);
            this.deactivate.setEnabled(true);
            this.eight.setEnabled(true);
            this.eightvolt.setEnabled(true);
            this.enter.setEnabled(true);
            this.five.setEnabled(true);
            this.fivevolt.setEnabled(true);
            this.four.setEnabled(true);
            this.fourvolt.setEnabled(true);
            this.nine.setEnabled(true);
            this.one.setEnabled(true);
            this.onevolt.setEnabled(true);
            this.resume.setEnabled(true);
            this.servicecompleted.setEnabled(true);
            this.seven.setEnabled(true);
            this.sevenvolt.setEnabled(true);
            this.six.setEnabled(true);
            this.sixvolt.setEnabled(true);
            this.starttripbtn.setEnabled(true);
            this.three.setEnabled(true);
            this.threevolt.setEnabled(true);
            this.two.setEnabled(true);
            this.twovolt.setEnabled(true);
            this.zero.setEnabled(true);
        } else if (!EngineButton.isSelected()) {
            config.sendEvent(new VehicleRunning(false));
            this.STOPcalibratebutton.setEnabled(false);
            this.acivate.setEnabled(true);
            this.averagespeedbtn.setEnabled(false);
            this.brake.setEnabled(false);
            this.calibratebutton.setEnabled(false);
            this.deactivate.setEnabled(false);
            this.eight.setEnabled(false);
            this.eightvolt.setEnabled(false);
            this.enter.setEnabled(false);
            this.five.setEnabled(false);
            this.fivevolt.setEnabled(false);
            this.four.setEnabled(false);
            this.fourvolt.setEnabled(false);
            this.nine.setEnabled(false);
            this.one.setEnabled(false);
            this.onevolt.setEnabled(false);
            this.resume.setEnabled(false);
            this.servicecompleted.setEnabled(false);
            this.seven.setEnabled(false);
            this.sevenvolt.setEnabled(false);
            this.six.setEnabled(false);
            this.sixvolt.setEnabled(false);
            this.starttripbtn.setEnabled(false);
            this.three.setEnabled(false);
            this.threevolt.setEnabled(false);
            this.two.setEnabled(false);
            this.twovolt.setEnabled(false);
            this.zero.setEnabled(false);
        }

    }//GEN-LAST:event_EngineButtonActionPerformed

    private void onevoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onevoltActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(1));
    }//GEN-LAST:event_onevoltActionPerformed

    private void fourvoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourvoltActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(4));
    }//GEN-LAST:event_fourvoltActionPerformed

    private void fivevoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivevoltActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(5));
    }//GEN-LAST:event_fivevoltActionPerformed

    private void sixvoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixvoltActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(6));
    }//GEN-LAST:event_sixvoltActionPerformed

    private void sevenvoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenvoltActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(7));
    }//GEN-LAST:event_sevenvoltActionPerformed

    private void eightvoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightvoltActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(8));
    }//GEN-LAST:event_eightvoltActionPerformed

    private void deactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new CruiseControlMonitoring(Integer.parseInt(getCurrentSpeed().getText()), CruiseControlCommand.DEACTIVATE));
    }//GEN-LAST:event_deactivateActionPerformed

    private void currentSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentSpeedActionPerformed

    private void calibratebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calibratebuttonActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new Calibrating("START_CALIBRATE"));
    }//GEN-LAST:event_calibratebuttonActionPerformed

    private void STOPcalibratebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STOPcalibratebuttonActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new Calibrating("STOP_CALIBRATE"));
    }//GEN-LAST:event_STOPcalibratebuttonActionPerformed

    private void averageSpeedDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averageSpeedDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_averageSpeedDisplayActionPerformed

    private void distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanceActionPerformed

    private void CalibrationDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalibrationDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalibrationDistanceActionPerformed

    private void twovoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twovoltActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(2));
    }//GEN-LAST:event_twovoltActionPerformed

    private void threevoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threevoltActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(3));
    }//GEN-LAST:event_threevoltActionPerformed

    private void brakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brakeActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new SpeedEvent(-1));
    }//GEN-LAST:event_brakeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new CruiseControlMonitoring(Integer.parseInt(getCurrentSpeed().getText()), CruiseControlCommand.RESUME));
    }//GEN-LAST:event_resumeActionPerformed

    private void acivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acivateActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new CruiseControlMonitoring(Integer.parseInt(getCurrentSpeed().getText()), CruiseControlCommand.ACTIVATE));

    }//GEN-LAST:event_acivateActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "0");
    }//GEN-LAST:event_zeroActionPerformed

    private void fuelEnteredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelEnteredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelEnteredActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "2");
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "3");
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "6");
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "8");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText(getFuelEntered().getText() + "9");
    }//GEN-LAST:event_nineActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        config.sendEvent(new FuelConsumptionMonitoring(Integer.parseInt(getFuelEntered().getText())));
        getFuelEntered().setText("");

    }//GEN-LAST:event_enterActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        getFuelEntered().setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void servicecompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicecompletedActionPerformed
        if(getServicecompleted().isSelected()){
            this.oilLabel.setIcon(null);
            this.oilLabel.revalidate();
            this.airfilter.setIcon(null);
            this.airfilter.revalidate();
            this.major.setIcon(null);
            this.major.revalidate();
            this.servicecompleted.setSelected(false);
            this.servicecompleted.setEnabled(false);
            config.sendEvent(new MaintenanceMonitoring(false));}
    }//GEN-LAST:event_servicecompletedActionPerformed

    private void starttripbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starttripbtnActionPerformed
       config.sendEvent(new AverageSpeedMonitoring("START_TRIP"));
    }//GEN-LAST:event_starttripbtnActionPerformed

    private void averagespeedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averagespeedbtnActionPerformed
         config.sendEvent(new AverageSpeedMonitoring("AVERAGE_SPEED"));
    }//GEN-LAST:event_averagespeedbtnActionPerformed

    private void jPanel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4PropertyChange

    public JToggleButton getSTOPcalibratebutton() {
        return STOPcalibratebutton;
    }

    public JButton getAcivate() {
        return acivate;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public JToggleButton getBrake() {
        return brake;
    }

    public JToggleButton getCalibratebutton() {
        return calibratebutton;
    }

    public JTextField getDriveShaftPulse() {
        return driveShaftPulse;
    }

    public JToggleButton getDeactivate() {
        return deactivate;
    }

    public JButton getEight() {
        return eight;
    }

    public JButton getEightvolt() {
        return eightvolt;
    }

    public JButton getEnter() {
        return enter;
    }

    public JButton getFive() {
        return five;
    }

    public JTextField getFuelEntered() {
        return fuelEntered;
    }

    public JButton getFivevolt() {
        return fivevolt;
    }

    public JButton getFour() {
        return four;
    }

    public JButton getFourvolt() {
        return fourvolt;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }


    public JPanel getKeyboard() {
        return keyboard;
    }

    public JButton getNine() {
        return nine;
    }

    public JButton getOne() {
        return one;
    }

    public JButton getOnevolt() {
        return onevolt;
    }

    public JToggleButton getResume() {
        return resume;
    }

    

    public JButton getSeven() {
        return seven;
    }

    public JButton getSevenvolt() {
        return sevenvolt;
    }

    public JButton getSix() {
        return six;
    }

    public JButton getSixvolt() {
        return sixvolt;
    }

    public JButton getThree() {
        return three;
    }

    public JButton getThreevolt() {
        return threevolt;
    }

    public JButton getTwo() {
        return two;
    }

    public JButton getTwovolt() {
        return twovolt;
    }

    public JButton getZero() {
        return zero;
    }

    public JTextField getCurrentSpeed() {
        return currentSpeed;
    }

    public JTextField getAverageSpeedDisplay() {
        return averageSpeedDisplay;
    }

    public JTextField getDistance() {
        return distance;
    }

    public JTextField getCalibrationDistance() {
        return CalibrationDistance;
    }

    public JLabel getAirfilter() {
        return airfilter;
    }

    public JLabel getMajor() {
        return major;
    }

    public JLabel getOilLabel() {
        return oilLabel;
    }

    public JToggleButton getEngineButton() {
        return EngineButton;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CalibrationDistance;
    private javax.swing.JPanel CruiseControl;
    private javax.swing.JToggleButton EngineButton;
    private javax.swing.JToggleButton STOPcalibratebutton;
    private javax.swing.JButton acivate;
    private javax.swing.JLabel airfilter;
    private javax.swing.JTextField averageSpeedDisplay;
    private javax.swing.JPanel averagespeed;
    private javax.swing.JButton averagespeedbtn;
    private javax.swing.JToggleButton brake;
    private javax.swing.JToggleButton calibratebutton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField currentSpeed;
    private javax.swing.JToggleButton deactivate;
    private javax.swing.JTextField distance;
    private javax.swing.JTextField driveShaftPulse;
    private javax.swing.JButton eight;
    private javax.swing.JButton eightvolt;
    private javax.swing.JButton enter;
    private javax.swing.JButton five;
    private javax.swing.JButton fivevolt;
    private javax.swing.JButton four;
    private javax.swing.JButton fourvolt;
    private javax.swing.JTextField fuelEntered;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel keyboard;
    private javax.swing.JLabel major;
    private javax.swing.JButton nine;
    private javax.swing.JLabel oilLabel;
    private javax.swing.JButton one;
    private javax.swing.JButton onevolt;
    private javax.swing.JToggleButton resume;
    private javax.swing.JToggleButton servicecompleted;
    private javax.swing.JButton seven;
    private javax.swing.JButton sevenvolt;
    private javax.swing.JButton six;
    private javax.swing.JButton sixvolt;
    private javax.swing.JButton starttripbtn;
    private javax.swing.JButton three;
    private javax.swing.JButton threevolt;
    private javax.swing.JButton two;
    private javax.swing.JButton twovolt;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
